//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenFlier.Desktop.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Backend {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Backend() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenFlier.Desktop.Localization.Backend", typeof(Backend).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for updates... 的本地化字符串。
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command is empty. 的本地化字符串。
        /// </summary>
        public static string CommandEmpty {
            get {
                return ResourceManager.GetString("CommandEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommandInputSource is not specified. 的本地化字符串。
        /// </summary>
        public static string CommandInputSourceNotSpecified {
            get {
                return ResourceManager.GetString("CommandInputSourceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config File (*.json)|*.json 的本地化字符串。
        /// </summary>
        public static string ConfigFileFilter {
            get {
                return ResourceManager.GetString("ConfigFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified connect code is not in the correct format. 的本地化字符串。
        /// </summary>
        public static string ConnectCodeFormatError {
            get {
                return ResourceManager.GetString("ConnectCodeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading update to {0} ... 的本地化字符串。
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred while checking for updates. 的本地化字符串。
        /// </summary>
        public static string ErrorCheckingForUpdates {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while downloading update to {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorDownloadingUpdate {
            get {
                return ResourceManager.GetString("ErrorDownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple IP Addresses 的本地化字符串。
        /// </summary>
        public static string MultipleAddresses {
            get {
                return ResourceManager.GetString("MultipleAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No compatible plugin for command {0}. 的本地化字符串。
        /// </summary>
        public static string NoCompatiblePlugin {
            get {
                return ResourceManager.GetString("NoCompatiblePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will overwrite existing config file.
        ///Continue? 的本地化字符串。
        /// </summary>
        public static string OverwriteConfigWarning {
            get {
                return ResourceManager.GetString("OverwriteConfigWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart to install update to {0}. 的本地化字符串。
        /// </summary>
        public static string ReadyToRestart {
            get {
                return ResourceManager.GetString("ReadyToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlier is up-to-date. 的本地化字符串。
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current user has task waiting to finish.
        ///Try again later or use the &quot;force&quot; command. 的本地化字符串。
        /// </summary>
        public static string UserBuzy {
            get {
                return ResourceManager.GetString("UserBuzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command not executed. 的本地化字符串。
        /// </summary>
        public static string UserCommandFailed {
            get {
                return ResourceManager.GetString("UserCommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 With Admin Privilege 的本地化字符串。
        /// </summary>
        public static string WithAdminPrivilege {
            get {
                return ResourceManager.GetString("WithAdminPrivilege", resourceCulture);
            }
        }
    }
}
