//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenFlier.Desktop.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenFlier.Desktop.Localization.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlier Insider
        ///Subject to changed. 的本地化字符串。
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acknowledgements 的本地化字符串。
        /// </summary>
        public static string Acknowledgements {
            get {
                return ResourceManager.GetString("Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more plugins requires admin privilege. 的本地化字符串。
        /// </summary>
        public static string AdminPrivilegeDescription {
            get {
                return ResourceManager.GetString("AdminPrivilegeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin Privilege Required 的本地化字符串。
        /// </summary>
        public static string AdminPrivilegeTitle {
            get {
                return ResourceManager.GetString("AdminPrivilegeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearances 的本地化字符串。
        /// </summary>
        public static string AppearancesTitle {
            get {
                return ResourceManager.GetString("AppearancesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string ApplyButtonContent {
            get {
                return ResourceManager.GetString("ApplyButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommandInput Plugins 的本地化字符串。
        /// </summary>
        public static string CommandInputPluginsTitle {
            get {
                return ResourceManager.GetString("CommandInputPluginsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommandInput Source 的本地化字符串。
        /// </summary>
        public static string CommandInputSourceTitle {
            get {
                return ResourceManager.GetString("CommandInputSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommandInput Users 的本地化字符串。
        /// </summary>
        public static string CommandInputUserListTitle {
            get {
                return ResourceManager.GetString("CommandInputUserListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure 的本地化字符串。
        /// </summary>
        public static string ConfigureButton {
            get {
                return ResourceManager.GetString("ConfigureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue 的本地化字符串。
        /// </summary>
        public static string ContinueText {
            get {
                return ResourceManager.GetString("ContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 2023, OpenFlier Contributors. All rights reserved. 的本地化字符串。
        /// </summary>
        public static string CopyrightString {
            get {
                return ResourceManager.GetString("CopyrightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable the plugins temporarily and continue 的本地化字符串。
        /// </summary>
        public static string DisableAndContinue {
            get {
                return ResourceManager.GetString("DisableAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZY ClassHelper sends its version code to your pad while transmitting image.
        ///Specified the latest version code here. 的本地化字符串。
        /// </summary>
        public static string EmulatedVersionDescription {
            get {
                return ResourceManager.GetString("EmulatedVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emulated Version 的本地化字符串。
        /// </summary>
        public static string EmulatedVersionTitle {
            get {
                return ResourceManager.GetString("EmulatedVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Window Effects 的本地化字符串。
        /// </summary>
        public static string EnableWindowEffectsCheckBoxContent {
            get {
                return ResourceManager.GetString("EnableWindowEffectsCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable window effects, which means Mica on Windows 11, and Aero on Windows 7. 的本地化字符串。
        /// </summary>
        public static string EnableWindowEffectsDescription {
            get {
                return ResourceManager.GetString("EnableWindowEffectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Effects 的本地化字符串。
        /// </summary>
        public static string EnableWindowEffectsTitle {
            get {
                return ResourceManager.GetString("EnableWindowEffectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Default Config 的本地化字符串。
        /// </summary>
        public static string ExportDefaultConfigButton {
            get {
                return ResourceManager.GetString("ExportDefaultConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export default config to a specified location for manual editing. 的本地化字符串。
        /// </summary>
        public static string ExportDefaultConfigDescription {
            get {
                return ResourceManager.GetString("ExportDefaultConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string FileTitle {
            get {
                return ResourceManager.GetString("FileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some experimental features, just for fun! 的本地化字符串。
        /// </summary>
        public static string FunZoneDescription {
            get {
                return ResourceManager.GetString("FunZoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fun Zone 的本地化字符串。
        /// </summary>
        public static string FunZoneTitle {
            get {
                return ResourceManager.GetString("FunZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Repository 的本地化字符串。
        /// </summary>
        public static string GithubHyperLink {
            get {
                return ResourceManager.GetString("GithubHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading Services... 的本地化字符串。
        /// </summary>
        public static string LoadingServiceString {
            get {
                return ResourceManager.GetString("LoadingServiceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machine Identifier 的本地化字符串。
        /// </summary>
        public static string MachineIdentifierTitle {
            get {
                return ResourceManager.GetString("MachineIdentifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT Server Port 的本地化字符串。
        /// </summary>
        public static string MqttServerPortTitle {
            get {
                return ResourceManager.GetString("MqttServerPortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT Service Plugins 的本地化字符串。
        /// </summary>
        public static string MqttServicePluginsTitle {
            get {
                return ResourceManager.GetString("MqttServicePluginsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OKText {
            get {
                return ResourceManager.GetString("OKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will overwrite existing config file.
        ///Continue? 的本地化字符串。
        /// </summary>
        public static string OverwriteConfigWarning {
            get {
                return ResourceManager.GetString("OverwriteConfigWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to Enable 的本地化字符串。
        /// </summary>
        public static string PluginEnabledCheckBox {
            get {
                return ResourceManager.GetString("PluginEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        public static string PluginsTitle {
            get {
                return ResourceManager.GetString("PluginsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reloading Services... 的本地化字符串。
        /// </summary>
        public static string ReloadingText {
            get {
                return ResourceManager.GetString("ReloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart OpenFlier as administrator 的本地化字符串。
        /// </summary>
        public static string RestartAsAdmin {
            get {
                return ResourceManager.GetString("RestartAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Default Config 的本地化字符串。
        /// </summary>
        public static string RestoreConfigButton {
            get {
                return ResourceManager.GetString("RestoreConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This action is irreversible.
        ///Are you sure to proceed? 的本地化字符串。
        /// </summary>
        public static string RestoreConfigConfirmText {
            get {
                return ResourceManager.GetString("RestoreConfigConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore all entries to default values.
        ///Plugins will need to be reinstalled. 的本地化字符串。
        /// </summary>
        public static string RestoreConfigDescription {
            get {
                return ResourceManager.GetString("RestoreConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Window 的本地化字符串。
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpecialChannels 的本地化字符串。
        /// </summary>
        public static string SpecialChannelsTitle {
            get {
                return ResourceManager.GetString("SpecialChannelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified Connect Code 的本地化字符串。
        /// </summary>
        public static string SpecifiedConnectCodeTitle {
            get {
                return ResourceManager.GetString("SpecifiedConnectCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified Machine Identifier 的本地化字符串。
        /// </summary>
        public static string SpecifiedMachineIdentifierTitle {
            get {
                return ResourceManager.GetString("SpecifiedMachineIdentifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UDP Broadcast Port 的本地化字符串。
        /// </summary>
        public static string UdpPortTitle {
            get {
                return ResourceManager.GetString("UdpPortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online updates are not supported on this version of OpenFlier. 的本地化字符串。
        /// </summary>
        public static string UpdatesDescription {
            get {
                return ResourceManager.GetString("UpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates 的本地化字符串。
        /// </summary>
        public static string UpdatesTitle {
            get {
                return ResourceManager.GetString("UpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use PNG Format 的本地化字符串。
        /// </summary>
        public static string UsePngCheckBoxContent {
            get {
                return ResourceManager.GetString("UsePngCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlier uses JPEG format as its default screenshot format.
        ///Check the following check box to use PNG format as the screenshot format, which can improve image quality, but increase latency. 的本地化字符串。
        /// </summary>
        public static string UsePngDescription {
            get {
                return ResourceManager.GetString("UsePngDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenshot Format 的本地化字符串。
        /// </summary>
        public static string UsePngTitle {
            get {
                return ResourceManager.GetString("UsePngTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Identifier 的本地化字符串。
        /// </summary>
        public static string UserIdentifierTitle {
            get {
                return ResourceManager.GetString("UserIdentifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all frames of a video, set timing intervals, and play! (10~20 fps recommanded. May use ffmpeg to extract frames manually.) 的本地化字符串。
        /// </summary>
        public static string VideoPlayDescription {
            get {
                return ResourceManager.GetString("VideoPlayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All Frames 的本地化字符串。
        /// </summary>
        public static string VideoPlayOpenButton {
            get {
                return ResourceManager.GetString("VideoPlayOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play A Video! 的本地化字符串。
        /// </summary>
        public static string VideoPlayTitle {
            get {
                return ResourceManager.GetString("VideoPlayTitle", resourceCulture);
            }
        }
    }
}
