// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: utils/Matrix.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from utils/Matrix.proto</summary>
public static partial class MatrixReflection {

  #region Descriptor
  /// <summary>File descriptor for utils/Matrix.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MatrixReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJ1dGlscy9NYXRyaXgucHJvdG8aGWdvb2dsZS9wcm90b2J1Zi9hbnkucHJv",
          "dG8iqQEKBk1hdHJpeBIRCglldmVudFRpbWUYASABKAMSDgoGc2NhbGVYGAIg",
          "ASgCEg0KBXNrZXdYGAMgASgCEg4KBnRyYW5zWBgEIAEoAhINCgVza2V3WRgF",
          "IAEoAhIOCgZzY2FsZVkYBiABKAISDgoGdHJhbnNZGAcgASgCEg4KBnBlclNw",
          "MBgIIAEoAhIOCgZwZXJTcDEYCSABKAISDgoGcGVyU3AyGAogASgCQhsKDmNv",
          "bS56eWtqLmJvYXJkQglFenlNYXRyaXhiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Matrix), global::Matrix.Parser, new[]{ "EventTime", "ScaleX", "SkewX", "TransX", "SkewY", "ScaleY", "TransY", "PerSp0", "PerSp1", "PerSp2" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Matrix : pb::IMessage<Matrix>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Matrix> _parser = new pb::MessageParser<Matrix>(() => new Matrix());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Matrix> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MatrixReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Matrix() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Matrix(Matrix other) : this() {
    eventTime_ = other.eventTime_;
    scaleX_ = other.scaleX_;
    skewX_ = other.skewX_;
    transX_ = other.transX_;
    skewY_ = other.skewY_;
    scaleY_ = other.scaleY_;
    transY_ = other.transY_;
    perSp0_ = other.perSp0_;
    perSp1_ = other.perSp1_;
    perSp2_ = other.perSp2_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Matrix Clone() {
    return new Matrix(this);
  }

  /// <summary>Field number for the "eventTime" field.</summary>
  public const int EventTimeFieldNumber = 1;
  private long eventTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long EventTime {
    get { return eventTime_; }
    set {
      eventTime_ = value;
    }
  }

  /// <summary>Field number for the "scaleX" field.</summary>
  public const int ScaleXFieldNumber = 2;
  private float scaleX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float ScaleX {
    get { return scaleX_; }
    set {
      scaleX_ = value;
    }
  }

  /// <summary>Field number for the "skewX" field.</summary>
  public const int SkewXFieldNumber = 3;
  private float skewX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float SkewX {
    get { return skewX_; }
    set {
      skewX_ = value;
    }
  }

  /// <summary>Field number for the "transX" field.</summary>
  public const int TransXFieldNumber = 4;
  private float transX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float TransX {
    get { return transX_; }
    set {
      transX_ = value;
    }
  }

  /// <summary>Field number for the "skewY" field.</summary>
  public const int SkewYFieldNumber = 5;
  private float skewY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float SkewY {
    get { return skewY_; }
    set {
      skewY_ = value;
    }
  }

  /// <summary>Field number for the "scaleY" field.</summary>
  public const int ScaleYFieldNumber = 6;
  private float scaleY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float ScaleY {
    get { return scaleY_; }
    set {
      scaleY_ = value;
    }
  }

  /// <summary>Field number for the "transY" field.</summary>
  public const int TransYFieldNumber = 7;
  private float transY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float TransY {
    get { return transY_; }
    set {
      transY_ = value;
    }
  }

  /// <summary>Field number for the "perSp0" field.</summary>
  public const int PerSp0FieldNumber = 8;
  private float perSp0_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PerSp0 {
    get { return perSp0_; }
    set {
      perSp0_ = value;
    }
  }

  /// <summary>Field number for the "perSp1" field.</summary>
  public const int PerSp1FieldNumber = 9;
  private float perSp1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PerSp1 {
    get { return perSp1_; }
    set {
      perSp1_ = value;
    }
  }

  /// <summary>Field number for the "perSp2" field.</summary>
  public const int PerSp2FieldNumber = 10;
  private float perSp2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PerSp2 {
    get { return perSp2_; }
    set {
      perSp2_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Matrix);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Matrix other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EventTime != other.EventTime) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ScaleX, other.ScaleX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SkewX, other.SkewX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TransX, other.TransX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SkewY, other.SkewY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ScaleY, other.ScaleY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TransY, other.TransY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PerSp0, other.PerSp0)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PerSp1, other.PerSp1)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PerSp2, other.PerSp2)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EventTime != 0L) hash ^= EventTime.GetHashCode();
    if (ScaleX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ScaleX);
    if (SkewX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SkewX);
    if (TransX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TransX);
    if (SkewY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SkewY);
    if (ScaleY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ScaleY);
    if (TransY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TransY);
    if (PerSp0 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PerSp0);
    if (PerSp1 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PerSp1);
    if (PerSp2 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PerSp2);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EventTime != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(EventTime);
    }
    if (ScaleX != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(ScaleX);
    }
    if (SkewX != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(SkewX);
    }
    if (TransX != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(TransX);
    }
    if (SkewY != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(SkewY);
    }
    if (ScaleY != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(ScaleY);
    }
    if (TransY != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(TransY);
    }
    if (PerSp0 != 0F) {
      output.WriteRawTag(69);
      output.WriteFloat(PerSp0);
    }
    if (PerSp1 != 0F) {
      output.WriteRawTag(77);
      output.WriteFloat(PerSp1);
    }
    if (PerSp2 != 0F) {
      output.WriteRawTag(85);
      output.WriteFloat(PerSp2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EventTime != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(EventTime);
    }
    if (ScaleX != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(ScaleX);
    }
    if (SkewX != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(SkewX);
    }
    if (TransX != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(TransX);
    }
    if (SkewY != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(SkewY);
    }
    if (ScaleY != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(ScaleY);
    }
    if (TransY != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(TransY);
    }
    if (PerSp0 != 0F) {
      output.WriteRawTag(69);
      output.WriteFloat(PerSp0);
    }
    if (PerSp1 != 0F) {
      output.WriteRawTag(77);
      output.WriteFloat(PerSp1);
    }
    if (PerSp2 != 0F) {
      output.WriteRawTag(85);
      output.WriteFloat(PerSp2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EventTime != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EventTime);
    }
    if (ScaleX != 0F) {
      size += 1 + 4;
    }
    if (SkewX != 0F) {
      size += 1 + 4;
    }
    if (TransX != 0F) {
      size += 1 + 4;
    }
    if (SkewY != 0F) {
      size += 1 + 4;
    }
    if (ScaleY != 0F) {
      size += 1 + 4;
    }
    if (TransY != 0F) {
      size += 1 + 4;
    }
    if (PerSp0 != 0F) {
      size += 1 + 4;
    }
    if (PerSp1 != 0F) {
      size += 1 + 4;
    }
    if (PerSp2 != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Matrix other) {
    if (other == null) {
      return;
    }
    if (other.EventTime != 0L) {
      EventTime = other.EventTime;
    }
    if (other.ScaleX != 0F) {
      ScaleX = other.ScaleX;
    }
    if (other.SkewX != 0F) {
      SkewX = other.SkewX;
    }
    if (other.TransX != 0F) {
      TransX = other.TransX;
    }
    if (other.SkewY != 0F) {
      SkewY = other.SkewY;
    }
    if (other.ScaleY != 0F) {
      ScaleY = other.ScaleY;
    }
    if (other.TransY != 0F) {
      TransY = other.TransY;
    }
    if (other.PerSp0 != 0F) {
      PerSp0 = other.PerSp0;
    }
    if (other.PerSp1 != 0F) {
      PerSp1 = other.PerSp1;
    }
    if (other.PerSp2 != 0F) {
      PerSp2 = other.PerSp2;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EventTime = input.ReadInt64();
          break;
        }
        case 21: {
          ScaleX = input.ReadFloat();
          break;
        }
        case 29: {
          SkewX = input.ReadFloat();
          break;
        }
        case 37: {
          TransX = input.ReadFloat();
          break;
        }
        case 45: {
          SkewY = input.ReadFloat();
          break;
        }
        case 53: {
          ScaleY = input.ReadFloat();
          break;
        }
        case 61: {
          TransY = input.ReadFloat();
          break;
        }
        case 69: {
          PerSp0 = input.ReadFloat();
          break;
        }
        case 77: {
          PerSp1 = input.ReadFloat();
          break;
        }
        case 85: {
          PerSp2 = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EventTime = input.ReadInt64();
          break;
        }
        case 21: {
          ScaleX = input.ReadFloat();
          break;
        }
        case 29: {
          SkewX = input.ReadFloat();
          break;
        }
        case 37: {
          TransX = input.ReadFloat();
          break;
        }
        case 45: {
          SkewY = input.ReadFloat();
          break;
        }
        case 53: {
          ScaleY = input.ReadFloat();
          break;
        }
        case 61: {
          TransY = input.ReadFloat();
          break;
        }
        case 69: {
          PerSp0 = input.ReadFloat();
          break;
        }
        case 77: {
          PerSp1 = input.ReadFloat();
          break;
        }
        case 85: {
          PerSp2 = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
