// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: utils/Paint.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from utils/Paint.proto</summary>
public static partial class PaintReflection {

  #region Descriptor
  /// <summary>File descriptor for utils/Paint.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PaintReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChF1dGlscy9QYWludC5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90",
          "byJrCgVQYWludBINCgV3aWR0aBgBIAEoAhINCgVjb2xvchgCIAEoBRIPCgdz",
          "cGFjaW5nGAMgASgCEhIKCml0ZW1MZW5ndGgYBCABKAISDQoFc3R5bGUYBSAB",
          "KAUSEAoIdGV4dFNpemUYBiABKAJCGgoOY29tLnp5a2ouYm9hcmRCCEV6eVBh",
          "aW50YgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Paint), global::Paint.Parser, new[]{ "Width", "Color", "Spacing", "ItemLength", "Style", "TextSize" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Paint : pb::IMessage<Paint>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Paint> _parser = new pb::MessageParser<Paint>(() => new Paint());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Paint> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PaintReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Paint() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Paint(Paint other) : this() {
    width_ = other.width_;
    color_ = other.color_;
    spacing_ = other.spacing_;
    itemLength_ = other.itemLength_;
    style_ = other.style_;
    textSize_ = other.textSize_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Paint Clone() {
    return new Paint(this);
  }

  /// <summary>Field number for the "width" field.</summary>
  public const int WidthFieldNumber = 1;
  private float width_;
  /// <summary>
  ///画笔宽度
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Width {
    get { return width_; }
    set {
      width_ = value;
    }
  }

  /// <summary>Field number for the "color" field.</summary>
  public const int ColorFieldNumber = 2;
  private int color_;
  /// <summary>
  ///画笔颜色
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Color {
    get { return color_; }
    set {
      color_ = value;
    }
  }

  /// <summary>Field number for the "spacing" field.</summary>
  public const int SpacingFieldNumber = 3;
  private float spacing_;
  /// <summary>
  ///实线间距 不是虚线的时候为0
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Spacing {
    get { return spacing_; }
    set {
      spacing_ = value;
    }
  }

  /// <summary>Field number for the "itemLength" field.</summary>
  public const int ItemLengthFieldNumber = 4;
  private float itemLength_;
  /// <summary>
  ///单个实线的长度
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float ItemLength {
    get { return itemLength_; }
    set {
      itemLength_ = value;
    }
  }

  /// <summary>Field number for the "style" field.</summary>
  public const int StyleFieldNumber = 5;
  private int style_;
  /// <summary>
  ///画笔的风格
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Style {
    get { return style_; }
    set {
      style_ = value;
    }
  }

  /// <summary>Field number for the "textSize" field.</summary>
  public const int TextSizeFieldNumber = 6;
  private float textSize_;
  /// <summary>
  ///文字的大小
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float TextSize {
    get { return textSize_; }
    set {
      textSize_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Paint);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Paint other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Width, other.Width)) return false;
    if (Color != other.Color) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Spacing, other.Spacing)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ItemLength, other.ItemLength)) return false;
    if (Style != other.Style) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TextSize, other.TextSize)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Width != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Width);
    if (Color != 0) hash ^= Color.GetHashCode();
    if (Spacing != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Spacing);
    if (ItemLength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ItemLength);
    if (Style != 0) hash ^= Style.GetHashCode();
    if (TextSize != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TextSize);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Width != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(Width);
    }
    if (Color != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Color);
    }
    if (Spacing != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Spacing);
    }
    if (ItemLength != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(ItemLength);
    }
    if (Style != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Style);
    }
    if (TextSize != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(TextSize);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Width != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(Width);
    }
    if (Color != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Color);
    }
    if (Spacing != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Spacing);
    }
    if (ItemLength != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(ItemLength);
    }
    if (Style != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Style);
    }
    if (TextSize != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(TextSize);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Width != 0F) {
      size += 1 + 4;
    }
    if (Color != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Color);
    }
    if (Spacing != 0F) {
      size += 1 + 4;
    }
    if (ItemLength != 0F) {
      size += 1 + 4;
    }
    if (Style != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Style);
    }
    if (TextSize != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Paint other) {
    if (other == null) {
      return;
    }
    if (other.Width != 0F) {
      Width = other.Width;
    }
    if (other.Color != 0) {
      Color = other.Color;
    }
    if (other.Spacing != 0F) {
      Spacing = other.Spacing;
    }
    if (other.ItemLength != 0F) {
      ItemLength = other.ItemLength;
    }
    if (other.Style != 0) {
      Style = other.Style;
    }
    if (other.TextSize != 0F) {
      TextSize = other.TextSize;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          Width = input.ReadFloat();
          break;
        }
        case 16: {
          Color = input.ReadInt32();
          break;
        }
        case 29: {
          Spacing = input.ReadFloat();
          break;
        }
        case 37: {
          ItemLength = input.ReadFloat();
          break;
        }
        case 40: {
          Style = input.ReadInt32();
          break;
        }
        case 53: {
          TextSize = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          Width = input.ReadFloat();
          break;
        }
        case 16: {
          Color = input.ReadInt32();
          break;
        }
        case 29: {
          Spacing = input.ReadFloat();
          break;
        }
        case 37: {
          ItemLength = input.ReadFloat();
          break;
        }
        case 40: {
          Style = input.ReadInt32();
          break;
        }
        case 53: {
          TextSize = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
