// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: plugin_pack.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenFlier.Plugin {

  /// <summary>Holder for reflection information generated from plugin_pack.proto</summary>
  public static partial class PluginPackReflection {

    #region Descriptor
    /// <summary>File descriptor for plugin_pack.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PluginPackReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFwbHVnaW5fcGFjay5wcm90byJDCgRGaWxlEhAKCGZpbGVuYW1lGAEgASgJ",
            "EhEKCWZpbGVfZGF0YRgCIAEoDBIWCg5pc19wbHVnaW5fbWFpbhgDIAEoCCLW",
            "AgoTU2luZ2xlUGx1Z2luUGFja2FnZRIgCgtwbHVnaW5fdHlwZRgBIAEoDjIL",
            "LlBsdWdpblR5cGUSEwoLcGx1Z2luX25hbWUYAiABKAkSFQoNcGx1Z2luX2F1",
            "dGhvchgDIAEoCRIZChFwbHVnaW5faWRlbnRpZmllchgEIAEoCRIWCg5wbHVn",
            "aW5fdmVyc2lvbhgFIAEoCRIaChJwbHVnaW5fZGVzY3JpcHRpb24YBiABKAkS",
            "KwojcmVxdWVzdGVkX21pbmltdW1fb3BlbmZsaWVyX3ZlcnNpb24YByABKAkS",
            "GQoRbXF0dF9tZXNzYWdlX3R5cGUYCCABKAUSIgoaY29tbWFuZF9pbnB1dF9j",
            "YWxsZXJfbmFtZXMYCSADKAkSIAoYcGx1Z2luX25lZWRfY29uZmlnX2VudHJ5",
            "GAogASgIEhQKBWZpbGVzGAsgAygLMgUuRmlsZSJyChBQbHVnaW5Db2xsZWN0",
            "aW9uEhcKD2NvbGxlY3Rpb25fbmFtZRgBIAEoCRIeChZjb2xsZWN0aW9uX2Rl",
            "c2NyaXB0aW9uGAIgASgJEiUKB3BsdWdpbnMYAyADKAsyFC5TaW5nbGVQbHVn",
            "aW5QYWNrYWdlKlUKClBsdWdpblR5cGUSFAoQVFlQRV9VTlNQRUNJRklFRBAA",
            "EhcKE01RVFRfU0VSVklDRV9QTFVHSU4QARIYChRDT01NQU5EX0lOUFVUX1BM",
            "VUdJThACQhOqAhBPcGVuRmxpZXIuUGx1Z2luYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::OpenFlier.Plugin.PluginType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenFlier.Plugin.File), global::OpenFlier.Plugin.File.Parser, new[]{ "Filename", "FileData", "IsPluginMain" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenFlier.Plugin.SinglePluginPackage), global::OpenFlier.Plugin.SinglePluginPackage.Parser, new[]{ "PluginType", "PluginName", "PluginAuthor", "PluginIdentifier", "PluginVersion", "PluginDescription", "RequestedMinimumOpenflierVersion", "MqttMessageType", "CommandInputCallerNames", "PluginNeedConfigEntry", "Files" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenFlier.Plugin.PluginCollection), global::OpenFlier.Plugin.PluginCollection.Parser, new[]{ "CollectionName", "CollectionDescription", "Plugins" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PluginType {
    [pbr::OriginalName("TYPE_UNSPECIFIED")] TypeUnspecified = 0,
    [pbr::OriginalName("MQTT_SERVICE_PLUGIN")] MqttServicePlugin = 1,
    [pbr::OriginalName("COMMAND_INPUT_PLUGIN")] CommandInputPlugin = 2,
  }

  #endregion

  #region Messages
  public sealed partial class File : pb::IMessage<File>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<File> _parser = new pb::MessageParser<File>(() => new File());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<File> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenFlier.Plugin.PluginPackReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public File() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public File(File other) : this() {
      filename_ = other.filename_;
      fileData_ = other.fileData_;
      isPluginMain_ = other.isPluginMain_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public File Clone() {
      return new File(this);
    }

    /// <summary>Field number for the "filename" field.</summary>
    public const int FilenameFieldNumber = 1;
    private string filename_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Filename {
      get { return filename_; }
      set {
        filename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "file_data" field.</summary>
    public const int FileDataFieldNumber = 2;
    private pb::ByteString fileData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString FileData {
      get { return fileData_; }
      set {
        fileData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "is_plugin_main" field.</summary>
    public const int IsPluginMainFieldNumber = 3;
    private bool isPluginMain_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsPluginMain {
      get { return isPluginMain_; }
      set {
        isPluginMain_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as File);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(File other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Filename != other.Filename) return false;
      if (FileData != other.FileData) return false;
      if (IsPluginMain != other.IsPluginMain) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Filename.Length != 0) hash ^= Filename.GetHashCode();
      if (FileData.Length != 0) hash ^= FileData.GetHashCode();
      if (IsPluginMain != false) hash ^= IsPluginMain.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Filename.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Filename);
      }
      if (FileData.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(FileData);
      }
      if (IsPluginMain != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsPluginMain);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Filename.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Filename);
      }
      if (FileData.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(FileData);
      }
      if (IsPluginMain != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsPluginMain);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Filename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Filename);
      }
      if (FileData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(FileData);
      }
      if (IsPluginMain != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(File other) {
      if (other == null) {
        return;
      }
      if (other.Filename.Length != 0) {
        Filename = other.Filename;
      }
      if (other.FileData.Length != 0) {
        FileData = other.FileData;
      }
      if (other.IsPluginMain != false) {
        IsPluginMain = other.IsPluginMain;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Filename = input.ReadString();
            break;
          }
          case 18: {
            FileData = input.ReadBytes();
            break;
          }
          case 24: {
            IsPluginMain = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Filename = input.ReadString();
            break;
          }
          case 18: {
            FileData = input.ReadBytes();
            break;
          }
          case 24: {
            IsPluginMain = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SinglePluginPackage : pb::IMessage<SinglePluginPackage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SinglePluginPackage> _parser = new pb::MessageParser<SinglePluginPackage>(() => new SinglePluginPackage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SinglePluginPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenFlier.Plugin.PluginPackReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SinglePluginPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SinglePluginPackage(SinglePluginPackage other) : this() {
      pluginType_ = other.pluginType_;
      pluginName_ = other.pluginName_;
      pluginAuthor_ = other.pluginAuthor_;
      pluginIdentifier_ = other.pluginIdentifier_;
      pluginVersion_ = other.pluginVersion_;
      pluginDescription_ = other.pluginDescription_;
      requestedMinimumOpenflierVersion_ = other.requestedMinimumOpenflierVersion_;
      mqttMessageType_ = other.mqttMessageType_;
      commandInputCallerNames_ = other.commandInputCallerNames_.Clone();
      pluginNeedConfigEntry_ = other.pluginNeedConfigEntry_;
      files_ = other.files_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SinglePluginPackage Clone() {
      return new SinglePluginPackage(this);
    }

    /// <summary>Field number for the "plugin_type" field.</summary>
    public const int PluginTypeFieldNumber = 1;
    private global::OpenFlier.Plugin.PluginType pluginType_ = global::OpenFlier.Plugin.PluginType.TypeUnspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenFlier.Plugin.PluginType PluginType {
      get { return pluginType_; }
      set {
        pluginType_ = value;
      }
    }

    /// <summary>Field number for the "plugin_name" field.</summary>
    public const int PluginNameFieldNumber = 2;
    private string pluginName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PluginName {
      get { return pluginName_; }
      set {
        pluginName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "plugin_author" field.</summary>
    public const int PluginAuthorFieldNumber = 3;
    private string pluginAuthor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PluginAuthor {
      get { return pluginAuthor_; }
      set {
        pluginAuthor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "plugin_identifier" field.</summary>
    public const int PluginIdentifierFieldNumber = 4;
    private string pluginIdentifier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PluginIdentifier {
      get { return pluginIdentifier_; }
      set {
        pluginIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "plugin_version" field.</summary>
    public const int PluginVersionFieldNumber = 5;
    private string pluginVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PluginVersion {
      get { return pluginVersion_; }
      set {
        pluginVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "plugin_description" field.</summary>
    public const int PluginDescriptionFieldNumber = 6;
    private string pluginDescription_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PluginDescription {
      get { return pluginDescription_; }
      set {
        pluginDescription_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "requested_minimum_openflier_version" field.</summary>
    public const int RequestedMinimumOpenflierVersionFieldNumber = 7;
    private string requestedMinimumOpenflierVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestedMinimumOpenflierVersion {
      get { return requestedMinimumOpenflierVersion_; }
      set {
        requestedMinimumOpenflierVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mqtt_message_type" field.</summary>
    public const int MqttMessageTypeFieldNumber = 8;
    private int mqttMessageType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MqttMessageType {
      get { return mqttMessageType_; }
      set {
        mqttMessageType_ = value;
      }
    }

    /// <summary>Field number for the "command_input_caller_names" field.</summary>
    public const int CommandInputCallerNamesFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_commandInputCallerNames_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> commandInputCallerNames_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> CommandInputCallerNames {
      get { return commandInputCallerNames_; }
    }

    /// <summary>Field number for the "plugin_need_config_entry" field.</summary>
    public const int PluginNeedConfigEntryFieldNumber = 10;
    private bool pluginNeedConfigEntry_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PluginNeedConfigEntry {
      get { return pluginNeedConfigEntry_; }
      set {
        pluginNeedConfigEntry_ = value;
      }
    }

    /// <summary>Field number for the "files" field.</summary>
    public const int FilesFieldNumber = 11;
    private static readonly pb::FieldCodec<global::OpenFlier.Plugin.File> _repeated_files_codec
        = pb::FieldCodec.ForMessage(90, global::OpenFlier.Plugin.File.Parser);
    private readonly pbc::RepeatedField<global::OpenFlier.Plugin.File> files_ = new pbc::RepeatedField<global::OpenFlier.Plugin.File>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenFlier.Plugin.File> Files {
      get { return files_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SinglePluginPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SinglePluginPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PluginType != other.PluginType) return false;
      if (PluginName != other.PluginName) return false;
      if (PluginAuthor != other.PluginAuthor) return false;
      if (PluginIdentifier != other.PluginIdentifier) return false;
      if (PluginVersion != other.PluginVersion) return false;
      if (PluginDescription != other.PluginDescription) return false;
      if (RequestedMinimumOpenflierVersion != other.RequestedMinimumOpenflierVersion) return false;
      if (MqttMessageType != other.MqttMessageType) return false;
      if(!commandInputCallerNames_.Equals(other.commandInputCallerNames_)) return false;
      if (PluginNeedConfigEntry != other.PluginNeedConfigEntry) return false;
      if(!files_.Equals(other.files_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PluginType != global::OpenFlier.Plugin.PluginType.TypeUnspecified) hash ^= PluginType.GetHashCode();
      if (PluginName.Length != 0) hash ^= PluginName.GetHashCode();
      if (PluginAuthor.Length != 0) hash ^= PluginAuthor.GetHashCode();
      if (PluginIdentifier.Length != 0) hash ^= PluginIdentifier.GetHashCode();
      if (PluginVersion.Length != 0) hash ^= PluginVersion.GetHashCode();
      if (PluginDescription.Length != 0) hash ^= PluginDescription.GetHashCode();
      if (RequestedMinimumOpenflierVersion.Length != 0) hash ^= RequestedMinimumOpenflierVersion.GetHashCode();
      if (MqttMessageType != 0) hash ^= MqttMessageType.GetHashCode();
      hash ^= commandInputCallerNames_.GetHashCode();
      if (PluginNeedConfigEntry != false) hash ^= PluginNeedConfigEntry.GetHashCode();
      hash ^= files_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PluginType != global::OpenFlier.Plugin.PluginType.TypeUnspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PluginType);
      }
      if (PluginName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PluginName);
      }
      if (PluginAuthor.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PluginAuthor);
      }
      if (PluginIdentifier.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PluginIdentifier);
      }
      if (PluginVersion.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PluginVersion);
      }
      if (PluginDescription.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PluginDescription);
      }
      if (RequestedMinimumOpenflierVersion.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(RequestedMinimumOpenflierVersion);
      }
      if (MqttMessageType != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MqttMessageType);
      }
      commandInputCallerNames_.WriteTo(output, _repeated_commandInputCallerNames_codec);
      if (PluginNeedConfigEntry != false) {
        output.WriteRawTag(80);
        output.WriteBool(PluginNeedConfigEntry);
      }
      files_.WriteTo(output, _repeated_files_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PluginType != global::OpenFlier.Plugin.PluginType.TypeUnspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) PluginType);
      }
      if (PluginName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PluginName);
      }
      if (PluginAuthor.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PluginAuthor);
      }
      if (PluginIdentifier.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PluginIdentifier);
      }
      if (PluginVersion.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PluginVersion);
      }
      if (PluginDescription.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PluginDescription);
      }
      if (RequestedMinimumOpenflierVersion.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(RequestedMinimumOpenflierVersion);
      }
      if (MqttMessageType != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MqttMessageType);
      }
      commandInputCallerNames_.WriteTo(ref output, _repeated_commandInputCallerNames_codec);
      if (PluginNeedConfigEntry != false) {
        output.WriteRawTag(80);
        output.WriteBool(PluginNeedConfigEntry);
      }
      files_.WriteTo(ref output, _repeated_files_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PluginType != global::OpenFlier.Plugin.PluginType.TypeUnspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PluginType);
      }
      if (PluginName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PluginName);
      }
      if (PluginAuthor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PluginAuthor);
      }
      if (PluginIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PluginIdentifier);
      }
      if (PluginVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PluginVersion);
      }
      if (PluginDescription.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PluginDescription);
      }
      if (RequestedMinimumOpenflierVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestedMinimumOpenflierVersion);
      }
      if (MqttMessageType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MqttMessageType);
      }
      size += commandInputCallerNames_.CalculateSize(_repeated_commandInputCallerNames_codec);
      if (PluginNeedConfigEntry != false) {
        size += 1 + 1;
      }
      size += files_.CalculateSize(_repeated_files_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SinglePluginPackage other) {
      if (other == null) {
        return;
      }
      if (other.PluginType != global::OpenFlier.Plugin.PluginType.TypeUnspecified) {
        PluginType = other.PluginType;
      }
      if (other.PluginName.Length != 0) {
        PluginName = other.PluginName;
      }
      if (other.PluginAuthor.Length != 0) {
        PluginAuthor = other.PluginAuthor;
      }
      if (other.PluginIdentifier.Length != 0) {
        PluginIdentifier = other.PluginIdentifier;
      }
      if (other.PluginVersion.Length != 0) {
        PluginVersion = other.PluginVersion;
      }
      if (other.PluginDescription.Length != 0) {
        PluginDescription = other.PluginDescription;
      }
      if (other.RequestedMinimumOpenflierVersion.Length != 0) {
        RequestedMinimumOpenflierVersion = other.RequestedMinimumOpenflierVersion;
      }
      if (other.MqttMessageType != 0) {
        MqttMessageType = other.MqttMessageType;
      }
      commandInputCallerNames_.Add(other.commandInputCallerNames_);
      if (other.PluginNeedConfigEntry != false) {
        PluginNeedConfigEntry = other.PluginNeedConfigEntry;
      }
      files_.Add(other.files_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PluginType = (global::OpenFlier.Plugin.PluginType) input.ReadEnum();
            break;
          }
          case 18: {
            PluginName = input.ReadString();
            break;
          }
          case 26: {
            PluginAuthor = input.ReadString();
            break;
          }
          case 34: {
            PluginIdentifier = input.ReadString();
            break;
          }
          case 42: {
            PluginVersion = input.ReadString();
            break;
          }
          case 50: {
            PluginDescription = input.ReadString();
            break;
          }
          case 58: {
            RequestedMinimumOpenflierVersion = input.ReadString();
            break;
          }
          case 64: {
            MqttMessageType = input.ReadInt32();
            break;
          }
          case 74: {
            commandInputCallerNames_.AddEntriesFrom(input, _repeated_commandInputCallerNames_codec);
            break;
          }
          case 80: {
            PluginNeedConfigEntry = input.ReadBool();
            break;
          }
          case 90: {
            files_.AddEntriesFrom(input, _repeated_files_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PluginType = (global::OpenFlier.Plugin.PluginType) input.ReadEnum();
            break;
          }
          case 18: {
            PluginName = input.ReadString();
            break;
          }
          case 26: {
            PluginAuthor = input.ReadString();
            break;
          }
          case 34: {
            PluginIdentifier = input.ReadString();
            break;
          }
          case 42: {
            PluginVersion = input.ReadString();
            break;
          }
          case 50: {
            PluginDescription = input.ReadString();
            break;
          }
          case 58: {
            RequestedMinimumOpenflierVersion = input.ReadString();
            break;
          }
          case 64: {
            MqttMessageType = input.ReadInt32();
            break;
          }
          case 74: {
            commandInputCallerNames_.AddEntriesFrom(ref input, _repeated_commandInputCallerNames_codec);
            break;
          }
          case 80: {
            PluginNeedConfigEntry = input.ReadBool();
            break;
          }
          case 90: {
            files_.AddEntriesFrom(ref input, _repeated_files_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PluginCollection : pb::IMessage<PluginCollection>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PluginCollection> _parser = new pb::MessageParser<PluginCollection>(() => new PluginCollection());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PluginCollection> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenFlier.Plugin.PluginPackReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PluginCollection() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PluginCollection(PluginCollection other) : this() {
      collectionName_ = other.collectionName_;
      collectionDescription_ = other.collectionDescription_;
      plugins_ = other.plugins_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PluginCollection Clone() {
      return new PluginCollection(this);
    }

    /// <summary>Field number for the "collection_name" field.</summary>
    public const int CollectionNameFieldNumber = 1;
    private string collectionName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CollectionName {
      get { return collectionName_; }
      set {
        collectionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "collection_description" field.</summary>
    public const int CollectionDescriptionFieldNumber = 2;
    private string collectionDescription_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CollectionDescription {
      get { return collectionDescription_; }
      set {
        collectionDescription_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "plugins" field.</summary>
    public const int PluginsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::OpenFlier.Plugin.SinglePluginPackage> _repeated_plugins_codec
        = pb::FieldCodec.ForMessage(26, global::OpenFlier.Plugin.SinglePluginPackage.Parser);
    private readonly pbc::RepeatedField<global::OpenFlier.Plugin.SinglePluginPackage> plugins_ = new pbc::RepeatedField<global::OpenFlier.Plugin.SinglePluginPackage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::OpenFlier.Plugin.SinglePluginPackage> Plugins {
      get { return plugins_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PluginCollection);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PluginCollection other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CollectionName != other.CollectionName) return false;
      if (CollectionDescription != other.CollectionDescription) return false;
      if(!plugins_.Equals(other.plugins_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CollectionName.Length != 0) hash ^= CollectionName.GetHashCode();
      if (CollectionDescription.Length != 0) hash ^= CollectionDescription.GetHashCode();
      hash ^= plugins_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CollectionName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CollectionName);
      }
      if (CollectionDescription.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CollectionDescription);
      }
      plugins_.WriteTo(output, _repeated_plugins_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CollectionName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CollectionName);
      }
      if (CollectionDescription.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CollectionDescription);
      }
      plugins_.WriteTo(ref output, _repeated_plugins_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CollectionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CollectionName);
      }
      if (CollectionDescription.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CollectionDescription);
      }
      size += plugins_.CalculateSize(_repeated_plugins_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PluginCollection other) {
      if (other == null) {
        return;
      }
      if (other.CollectionName.Length != 0) {
        CollectionName = other.CollectionName;
      }
      if (other.CollectionDescription.Length != 0) {
        CollectionDescription = other.CollectionDescription;
      }
      plugins_.Add(other.plugins_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CollectionName = input.ReadString();
            break;
          }
          case 18: {
            CollectionDescription = input.ReadString();
            break;
          }
          case 26: {
            plugins_.AddEntriesFrom(input, _repeated_plugins_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CollectionName = input.ReadString();
            break;
          }
          case 18: {
            CollectionDescription = input.ReadString();
            break;
          }
          case 26: {
            plugins_.AddEntriesFrom(ref input, _repeated_plugins_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
