//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenFlier {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenFlier.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlier Insider
        ///For testing purposes only. 的本地化字符串。
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearances 的本地化字符串。
        /// </summary>
        public static string AppearancesTitle {
            get {
                return ResourceManager.GetString("AppearancesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string ApplyButtonContent {
            get {
                return ResourceManager.GetString("ApplyButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommandInput Plugins 的本地化字符串。
        /// </summary>
        public static string CommandInputPluginsTitle {
            get {
                return ResourceManager.GetString("CommandInputPluginsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure 的本地化字符串。
        /// </summary>
        public static string ConfigureButton {
            get {
                return ResourceManager.GetString("ConfigureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue 的本地化字符串。
        /// </summary>
        public static string ContinueText {
            get {
                return ResourceManager.GetString("ContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 2023, OpenFlier Contributors. All rights reserved. 的本地化字符串。
        /// </summary>
        public static string CopyrightString {
            get {
                return ResourceManager.GetString("CopyrightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZY ClassHelper sends its version code to your pad while transmitting image.
        ///Specified the latest version code here. 的本地化字符串。
        /// </summary>
        public static string EmulatedVersionDescription {
            get {
                return ResourceManager.GetString("EmulatedVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emulated Version 的本地化字符串。
        /// </summary>
        public static string EmulatedVersionTitle {
            get {
                return ResourceManager.GetString("EmulatedVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Window Effects 的本地化字符串。
        /// </summary>
        public static string EnableWindowEffectsCheckBoxContent {
            get {
                return ResourceManager.GetString("EnableWindowEffectsCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable window effects, which means Mica on Windows 11, and Aero on Windows 7. 的本地化字符串。
        /// </summary>
        public static string EnableWindowEffectsDescription {
            get {
                return ResourceManager.GetString("EnableWindowEffectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window Effects 的本地化字符串。
        /// </summary>
        public static string EnableWindowEffectsTitle {
            get {
                return ResourceManager.GetString("EnableWindowEffectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string FileTitle {
            get {
                return ResourceManager.GetString("FileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading Services... 的本地化字符串。
        /// </summary>
        public static string LoadingServiceString {
            get {
                return ResourceManager.GetString("LoadingServiceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT Server Port 的本地化字符串。
        /// </summary>
        public static string MqttServerPortTitle {
            get {
                return ResourceManager.GetString("MqttServerPortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MQTT Service Plugins 的本地化字符串。
        /// </summary>
        public static string MqttServicePluginsTitle {
            get {
                return ResourceManager.GetString("MqttServicePluginsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        public static string PluginsTitle {
            get {
                return ResourceManager.GetString("PluginsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This device is connected to multiple networks, thus it has multiple IP Addresses.
        ///OpenFlier only works with one given address, select one from below: 的本地化字符串。
        /// </summary>
        public static string SelectNetworkInterfaceDescription {
            get {
                return ResourceManager.GetString("SelectNetworkInterfaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select An IP Address 的本地化字符串。
        /// </summary>
        public static string SelectNetworkInterfaceTitle {
            get {
                return ResourceManager.GetString("SelectNetworkInterfaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SpecialChannels 的本地化字符串。
        /// </summary>
        public static string SpecialChannelsTitle {
            get {
                return ResourceManager.GetString("SpecialChannelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified Connect Code 的本地化字符串。
        /// </summary>
        public static string SpecifiedConnectCodeTitle {
            get {
                return ResourceManager.GetString("SpecifiedConnectCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified Machine Identifier 的本地化字符串。
        /// </summary>
        public static string SpecifiedMachineIdentifierTitle {
            get {
                return ResourceManager.GetString("SpecifiedMachineIdentifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UDP Broadcast Port 的本地化字符串。
        /// </summary>
        public static string UdpPortTitle {
            get {
                return ResourceManager.GetString("UdpPortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online updates are not supported on this version of OpenFlier. 的本地化字符串。
        /// </summary>
        public static string UpdatesDescription {
            get {
                return ResourceManager.GetString("UpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates 的本地化字符串。
        /// </summary>
        public static string UpdatesTitle {
            get {
                return ResourceManager.GetString("UpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use PNG Format 的本地化字符串。
        /// </summary>
        public static string UsePngCheckBoxContent {
            get {
                return ResourceManager.GetString("UsePngCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlier uses JPEG format as its default screenshot format.
        ///Check the following check box to use PNG format as the screenshot format, which can improve image quality, but increase latency. 的本地化字符串。
        /// </summary>
        public static string UsePngDescription {
            get {
                return ResourceManager.GetString("UsePngDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenshot Format 的本地化字符串。
        /// </summary>
        public static string UsePngTitle {
            get {
                return ResourceManager.GetString("UsePngTitle", resourceCulture);
            }
        }
    }
}
