//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Installer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Installer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Improperly Displayed 的本地化字符串。
        /// </summary>
        public static string FontTestAbnormalButton {
            get {
                return ResourceManager.GetString("FontTestAbnormalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dismiss 的本地化字符串。
        /// </summary>
        public static string FontTestDismiss {
            get {
                return ResourceManager.GetString("FontTestDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlier takes adavantage of Microsoft&apos;s Segoe Fluent Icons to deliver a more consistent look with Windows.
        ///However, Segoe Fluent Icons is shipped by default only on Windows 11, and according to its EULA, we cannot ship the font together with this application.
        ///We have detected that Segoe Fluent Icons is not installed on this computer, but this could also be a false alarm, thus, we provided this test.
        ///The following icon is provided by Segoe Fluent Icons, which describes establishing a connection between  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string FontTestScreenDescription {
            get {
                return ResourceManager.GetString("FontTestScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Your Font Installation 的本地化字符串。
        /// </summary>
        public static string FontTestScreenTitle {
            get {
                return ResourceManager.GetString("FontTestScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installer 的本地化字符串。
        /// </summary>
        public static string InstallerName {
            get {
                return ResourceManager.GetString("InstallerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The installer will guide you through the installation process of OpenFlier.
        ///Before we get started, select your installation mode: 的本地化字符串。
        /// </summary>
        public static string InstallerWelcomeScreenDescription {
            get {
                return ResourceManager.GetString("InstallerWelcomeScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlier Installer 的本地化字符串。
        /// </summary>
        public static string InstallerWelcomeScreenTitle {
            get {
                return ResourceManager.GetString("InstallerWelcomeScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you have downloaded an offline package, or you would like to downgrade to a lower version, use this option.
        ///Please note: The installer will not verify your package. 的本地化字符串。
        /// </summary>
        public static string OfflineInstallDiscription {
            get {
                return ResourceManager.GetString("OfflineInstallDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Offline 的本地化字符串。
        /// </summary>
        public static string OfflineInstallString {
            get {
                return ResourceManager.GetString("OfflineInstallString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download the lastest package and install.
        ///The installer will verify the downloaded package. 的本地化字符串。
        /// </summary>
        public static string OnlineInstallDiscription {
            get {
                return ResourceManager.GetString("OnlineInstallDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download &amp; Install 的本地化字符串。
        /// </summary>
        public static string OnlineInstallString {
            get {
                return ResourceManager.GetString("OnlineInstallString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlier has multiple sources to download the package.
        ///Select one or use your own: 的本地化字符串。
        /// </summary>
        public static string SelectDownloadSourceScreenDescription {
            get {
                return ResourceManager.GetString("SelectDownloadSourceScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Download Source 的本地化字符串。
        /// </summary>
        public static string SelectDownloadSourceScreenTitle {
            get {
                return ResourceManager.GetString("SelectDownloadSourceScreenTitle", resourceCulture);
            }
        }
    }
}
